apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres
  - minio
  - zitadel
  - backend
  {% if cookiecutter.add_arq == "y" %}
  - redis
  - worker
  {% endif %}
  {% if cookiecutter.add_frontend == "y" %}
  - frontend
  {% endif %}
