{% if cookiecutter.use_stage_namespace == "y" %}
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  authentik-issuer: "https://auth-stage.{{ cookiecutter.project_slug }}.example.com/application/o/{{ cookiecutter.project_slug }}/"
{% endif %}
